- name: Install python
  hosts: ceph_servers
  become: yes
  gather_facts: no
  tasks:
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: "present"
      loop:
        - python3
        - wget

- name: Setup admin boostrap
  hosts: ceph_admins[0]
  become: yes
  gather_facts: yes
  roles:
    - ceph-boostrap-managers
