- name: Install python
  hosts: ceph_servers
  become: yes
  gather_facts: no
  tasks:
    - name: Install python
      dnf:
        name: "python3"
        state: "present"

- name: Setup admin boostrap
  hosts: ceph_admins[0]
  become: yes
  gather_facts: yes
  roles:
    - ceph-boostrap-managers
