- name: Setup and configure ceph pools
  hosts: ceph_mgrs
  become: yes
  gather_facts: yes
  tasks:
   - name: Setup and configure ceph pools
     import_role:
       name: ceph-add-pool
       vars_from: "{{ item }}"
     loop: "{{ pools_path_list }}"
