- name: Updating git on ansible 
  hosts: ansible
  become: yes
  gather_facts: no
  tasks:
  - name: Git pull
    git:
      repo: 'https://github.com/monkeyboy107/ansible-server'
      dest: '/etc/ansible'
      update: yes
