- name: Installing bareos-fd 
  hosts: all:!nas_servers:!hypervisor_servers:!bareos_servers
  become: yes
  gather_facts: no
  tasks:
  - name: Git pull
    git:
      repo: 'https://github.com/monkeyboy107/ansible-server'
      dest: '/etc/ansible'
      update: yes
