- name: Add ceph VMs
  hosts: proxmox_servers
  become: yes
  gather_facts: no
  vars:
    - guest_hosts: [{name: "test-vm.ihs.org", 'cores': 4, 'memory': 10240, 'sockets': 4, hdd: ['1G']}]
  roles:
    - proxmox-reconfigure-vm
