- name: Add ceph VMs
  hosts: test_hosts
  become: yes
  gather_facts: no
  tasks:
    - name: Loop through ansible_hosts
      include_role:
        name: proxmox-create-vm
        apply: 
          delegate_to: "ihs-ansible-01"
      with_inventory_hostnames: "{{ play_hosts }}"
      loop_control:
        loop_var: "guest_host"
