- name: Create the ceph_vm
  hosts: ceph_servers
  become: yes
  gather_facts: no
  tasks:
   - name: Create the VMs
     import_role:
       name: proxmox-create-vm
   - name: Start the VMs
     import_role:
       name: proxmox-start-vm
