- name: Create and configure the jenkins masters
  hosts: jenkins_masters
  become: yes
  gather_facts: no
  tasks:
   - name: Create the VMs
     import_role:
       name: proxmox-clone-vm
   - name: Start the VMs
     import_role:
       name: proxmox-start-vm
