---
# vm_list is all the vms that proxmox has with its corresponding vmid 
- name: Register the results of qm list
  shell: "qm list | awk '{print $2, $1}'"
  register: vm_list
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  run_once: true

# vm_name is dictionary of vm_list so that I can do vm_name.guest_hosts.name and it return the vmid
- name: Load varible with results from qm list
  set_fact:
    vm_name: "{{ vm_name | combine( {item.split(' ')[0]: item.split(' ')[1]} ) }}"
  loop: "{{ vm_list.stdout_lines }}"
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  run_once: true

# Reconfigures the VMs
- name: Reconfigure VM(s) CPU and RAM
  shell: "qm set {{ vm_name[ item.name ] }} --sockets {{ item.sockets }} --memory {{ item.memory }} --cores {{ item.cores }} -net0 e1000,tag={{ item.vlan_id }}"
  loop: "{{ guest_hosts | list }}"
  delegate_to: "{{ groups.proxmox_servers[0] }}"

# Divides the next section for if disks are requested
- name: Add disks
  include_tasks:
    file: block_storage.yaml
  loop: "{{ guest_hosts }}"
  loop_control:
    loop_var: "guest_host"

# Sets to boot with the hypervisor
- name: Boot VM with host
#  run_once: true
  shell: "qm set {{ vm_name[ item.name ] }} --onboot 1"
  loop: "{{ guest_hosts | list }}"
  when: start_on_boot
  delegate_to: "{{ groups.proxmox_servers[0] }}"

