---
- name: Update disks_in_use
  set_fact:
    disks_in_use: "{{ disks_in_use | union(item.device | split)}}"
  loop: "{{ ansible_facts.mounts }}"

- name: Remove all non usable disks
  set_fact:
    disks_not_in_use: "{{ disks_not_in_use | difference(item) }}"
  loop: "{{ unusable_disks }}"

- name: Remove disks_in_use from disks_all in order to update disks_not_in_use
  set_fact:
    disks_not_in_use: "{{ disks_not_in_use | union(item.0 | split)  }}"
  loop: "{{ disks_all | product(disks_in_use) | list }}"
  when:
    - "{{ item.0 not in item.1 }}"
    - "{{ disks_in_use }} != {{ disks_all }}"

- name: Display disks_in_use
  debug:
    msg: "{{ disks_in_use }}"

- name: Remove all non usable disks
  set_fact:
    disks_not_in_use: "{{ disks_not_in_use | difference(item) }}"
  loop: "{{ unusable_disks }}"

- name: Display disks_not_in_use
  debug:
    msg: "{{ disks_not_in_use }}"

- name: Clear file system
  filesystem:
    dev: "{{ item }}"
    force: true
    state: "absent"
  loop: "{{ disks_not_in_use }}"
