---
- name: Clone VM
  run_once: true
  shell: "qm clone {{ rocky_8_cloud_init_vmid }} {{ item }} --name {{ all_VMIDs_dict[item] }}"
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  loop: "{{ all_VMIDs_dict.keys() }}"
  when: all_VMIDs_dict[item] == guest_host
