---
- name: Clear results
  set_fact:
    results: ''

- name: Gather facts of disks ready state
  shell: "cephadm shell -- ceph orch device ls"
  register: results
  run_once: true
  delegate_to: "{{ groups.ceph_admins[0] }}"

- name: Check if disks are ready, if they are not then rerun
  when: results | length <= 2
#   - "{{ results != '' }}"
#   - "{{ results != None }}"
  include_tasks: "check-ceph-disks.yaml"
