- name: Looking up bareos-fd configs
  slurp:
    src: /etc/bareos/bareos-fd.d/director/bareos-dir.conf
  register: client_config

- name: Listifying config
  set_fact:
    config_list: "{{ client_config['content'] | b64decode | split('\n') }}"

- name: Pulling password
  set_fact:
    password: "{{ item }}"
  loop: "{{ config_list }}"
  when: "{{ 'Password' in item }}"

- name: Pushing bareos-fd config
  template:
    src: bareos-fd.conf.j2
    dest: "/etc/bareos/bareos-dir.d/client/{{ inventory_hostname_short }}-fd.conf"
    owner: bareos
    group: bareos
    mode: '0640'
  delegate_to: "{{ groups['bareos-dir_servers'][0] }}"

- name: Adding backup job
  template:
    src: bareos-job.conf.j2
    dest: "/etc/bareos/bareos-dir.d/job/backup-{{ inventory_hostname_short }}-fd.conf"
    owner: bareos
    group: bareos
    mode: '0640'
  delegate_to: "{{ groups['bareos-dir_servers'][0] }}"
  notify: "Reload bareos director"
