- name: "Create folder {{ nfs_local_mount_point }}"
  file: 
    path: "{{ nfs_local_mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Mount nfs-share
  mount:
    path: "{{ nfs_local_mount_point }}"
    src: "{{ nfs_fqdn }}:{{ nfs_remote_mount_point }}"
    fstype: nfs
    opts: defaults,_netdev,x-systemd.automount
    state: mounted
