---
- name: Retrieve mac address
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  shell: "qm config all_VMIDs_dict[guest_host] | grep net0 | tail -1 | awk {'print $2'} | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'"
  register: raw_mac_address

- name: Filter for the mac address	
  set_fact:
    mac_addresses: "{{ [ item.stdout | lower ] + mac_addresses }}"
  when: item.changed
  loop: "{{ raw_mac_address.results }}"
  
- name: Add kickstarts
  delegate_to: "{{ groups.ipxe_servers[0] }}"
  template: 
    src: kickstart.ks.j2
    dest: /var/www/html/rocky/8/ks/{{ mac }}.ks
  loop: "{{ mac_addresses }}"
    
- name: Add ipxe
  delegate_to: "{{ groups.ipxe_servers[0] }}"
  template:
    src: mac-address-template.ipxe.j2
    dest: /var/www/html/labnet/{{ ansible_host }}.ipxe
