---
- name: Retrieve VMIDs
  include_tasks: "retrieve_VMIDs.yaml"

# Zips the VMIDs with the hosts
- name: Assign unique ID for each VM
  set_fact:
    all_VMIDs_dict: "{{ all_VMIDs_dict | combine( {item.0: item.1} ) }}"
  loop: "{{ ID_list | zip(ansible_play_hosts) }}"

- name: Create the VMs
  loop: "{{ ansible_play_hosts }}"
  loop_control:
    loop_var: "guest_host"
  include_tasks: "create_vm.yaml"

#- name: Retrieve VMIDs
#  include_tasks: "retrieve_VMIDs.yaml"

- name: Add kickstarts and ipxe scripts
  loop: "{{ ID_list }}"
  loop_control:
    loop_var: "guest_vmid"
  include_tasks: "add_kickstarts_and_ipxe.yaml"
  
