---
- name: Check if VM is still installing
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  shell: "qm status {{ item }}"
  register: status
  loop: "{{ ID_list }}"

- name: Check if still running
  when: "'running' in item.stdout"
  set_fact:
    count: "{{ count | int + 1 }}"
  loop: "{{ status.results }}"

- name: If still running, restart {{ count }}
  when:
    - "running" in status.stdout 
    - count < 300
  include_tasks: "create_vm.yaml"

