---
- name: Power on VM
  shell: "qm start {{ vm_name[inventory_hostname]}}"
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  
- name: Wait for VM to fully boot
  wait_for:
    timeout: "{{ delay_for_boot }}"
  delegate_to: "{{ groups.proxmox_servers[0] }}"

- name: Reboot VM to update DNS
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  shell: "qm reboot {{ vm_name[inventory_hostname] }}"
  
- name: Wait for VM to start
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  wait_for:
    host: "{{ inventory_hostname }}"
#    delay: "{{ delay_for_boot }}"
    port: 22
    sleep: 10
    timeout: 600
