---
- name: Register the results of qm list
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  shell: "qm list | awk '{print $2, $1}'"
  register: vm_list

- name: Load varible with results from qm list
  delegate_to: "{{ groups.proxmox_servers[0] }}"
  set_fact:
    vm_name: "{{ vm_name | combine( {item.split(' ')[0]: item.split(' ')[1]} ) }}"
  loop: "{{ vm_list.stdout_lines }}"

- name: Wait for VM to start
  include_tasks: "clone_vm.yaml"
  tags: clone_vm

- name: Reset count
  set_fact:
    count: 0
  tags: create_vm

#- name: Wait for VM to start
#  include_tasks: "create_vm.yaml"
#  tags: create_vm
